adds kerberos template

diff --git a/templates/configure_active_directory.erb b/templates/configure_active_directory.erb
--- a/templates/configure_active_directory.erb
+++ b/templates/configure_active_directory.erb
@@ -9,7 +9,7 @@
 seconds=300
 #
 # post_join_delay seems to be necessary after joing domain
-post_join_delay=30
+post_join_delay=5
 #
 
 PROG=$(basename $0)
@@ -54,13 +54,13 @@ do
   esac
 done
 
-password='<%= scope.lookupvar('samba::server::ads::winbind_pass') -%>'
+password='<%= scope.lookupvar('samba::server::ads::ads_pass') -%>'
 
 # short hostname from facter
 my_hostname="<%= @hostname -%>"
 
 # what account do we use for net ads commands?
-winbind_acct="<%= scope.lookupvar('samba::server::ads::winbind_acct') -%>"
+ads_acct="<%= scope.lookupvar('samba::server::ads::ads_acct') -%>"
 
 # which realm will we be joining?
 my_realm="<%= scope.lookupvar('samba::server::ads::realm') -%>"
@@ -80,7 +80,7 @@ echo "Please do not kill me; I may be slow" >&2
 
 if [ "$action" = "leave" ]; then
   logger -st $PROG "Leaving AD domain"
-  $NET ads $action -U "${winbind_acct}%${password}" | grep Deleted && success=true || success=false
+  $NET ads $action -U "${ads_acct}%${password}" | grep Deleted && success=true || success=false
   kdestroy
   rm -f /etc/krb5.keytab
   if [ $success = "true" ]; then
@@ -102,7 +102,7 @@ ad_settle() {
 }
 
 # ldapmodify _does_ use the env var for sasl bind
-export KRB5CCNAME=$(umask 0077; mktemp -q winbind_cache.XXXXXXXX)
+export KRB5CCNAME=$(umask 0077; mktemp -q krb_cache.XXXXXXXX)
 
 if [ "$action" = "join" ]; then
     if [ "${target_ou}" != "" ]; then
@@ -112,7 +112,7 @@ if [ "$action" = "join" ]; then
     fi
 
     logger -st $PROG "Joining AD domain" >&2
-    $NET ads $action -U "${winbind_acct}%${password}" ${ou_parameter} \
+    $NET ads $action -U "${ads_acct}%${password}" ${ou_parameter} \
 	| grep Joined && success=true || success=false
 
 if [ $success = "false" ]; then
@@ -124,8 +124,8 @@ max_attempts=5
 for attempt in $(seq 1 $max_attempts); do
     echo "$attempt of $max_attempts:"
     ad_settle
-    echo "Getting TGT for ${winbind_acct}@${my_realm}" >&2
-    $EXPECT -c "spawn -noecho kinit -c $KRB5CCNAME ${winbind_acct}@${my_realm};
+    echo "Getting TGT for ${ads_acct}@${my_realm}" >&2
+    $EXPECT -c "spawn -noecho kinit -c $KRB5CCNAME ${ads_acct}@${my_realm};
         expect :;
         send {${password}};
         send \n;
@@ -133,12 +133,12 @@ for attempt in $(seq 1 $max_attempts); do
     klist -c $KRB5CCNAME &> /dev/null && break
 done
 
-if [ $(wbinfo -u|wc -l) != 0 ]; then
-	success=true
-else
-	echo "ERROR: return user list from AD is empty" >&2
-	success=false
-fi
+# if [ $(wbinfo -u|wc -l) != 0 ]; then
+# 	success=true
+# else
+# 	echo "ERROR: return user list from AD is empty" >&2
+# 	success=false
+# fi
 
 # get rid of cred cache
 kdestroy -c $KRB5CCNAME &> /dev/null
diff --git a/templates/verify_active_directory.erb b/templates/verify_active_directory.erb
--- a/templates/verify_active_directory.erb
+++ b/templates/verify_active_directory.erb
@@ -12,23 +12,16 @@ if ! [ -x "$EXPECT" ]; then
   exit 1
 fi
 
-#TODO
-#if ! check_kdc_time; then
-#  {
-#  echo "===================================="
-#  echo "WARNING: time offset seems too large"
-#  echo "===================================="
-#  } >&2
-#fi
-
-password='<%= scope.lookupvar('samba::server::ads::winbind_pass') -%>'
+password='<%= scope.lookupvar('samba::server::ads::ads_pass') -%>'
 
 # short hostname from facter
 my_hostname="<%= @hostname -%>"
 
-winbind_acct="<%= scope.lookupvar('samba::server::ads::winbind_acct') -%>"
+ads_acct="<%= scope.lookupvar('samba::server::ads::ads_acct') -%>"
 
-default_realm=$(grep -i '^[[:space:]]*realm.*=' /etc/samba/smb.conf | sed 's/ //g' | sed 's/realm=//g')
+kdc="<%= scope.lookupvar('samba::server::ads::kdc') -%>"
+
+default_realm="<%= scope.lookupvar('samba::server::ads::realm') -%>"
 
 # if we're still here, let's try the testjoin
 do_testjoin() {
@@ -49,6 +42,7 @@ do_testjoin
 if [ $? -ne 0 ]; then
   # get verbose failure info
   do_testjoin -d3
+  exit 1
 fi
 
 
@@ -56,18 +50,18 @@ fi
 # - get a TGT that enables us to query the attribute 'useraccountcontrol'
 # - confirm that AD trusts us for GSSAPI delegation
 
-export KRB5CCNAME=$(umask 0077; mktemp -q winbind_cache.XXXXXXXX)
+export KRB5CCNAME=$(umask 0077; mktemp -q krb_cache.XXXXXXXX)
 
 get_tgt() {
   (
-  $EXPECT -c "spawn -noecho kinit -c $KRB5CCNAME ${winbind_acct}@${default_realm};
-	expect :;
-	send {${password}};
-	send \n;
-	expect eof"
+  $EXPECT -c "spawn -noecho kinit -c $KRB5CCNAME ${ads_acct}@${default_realm};
+  expect :;
+  send {${password}};
+  send \n;
+  expect eof"
   ) &> /dev/null
-  klist -c $KRB5CCNAME &> /dev/null
-  return $?
+klist -c $KRB5CCNAME &> /dev/null
+return $?
 }
 
 # try this several times.
@@ -92,12 +86,12 @@ if [ $has_tgt -ne 0 ]; then
   logger -st $PROG "ERROR: failed to get TGT from AD"
   success=false
 else
-  if [ $(wbinfo -u|wc -l) != 0 ]; then
-    success=true
-  else
-    echo "ERROR: return user list from AD is empty" >&2
-    success=false
-  fi
+#   if [ $(wbinfo -u|wc -l) != 0 ]; then
+#     success=true
+#   else
+#     echo "ERROR: return user list from AD is empty" >&2
+#     success=false
+#   fi
 
   # get rid of cred cache
   kdestroy -c $KRB5CCNAME &> /dev/null
